// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RaftSnapshot.proto

#include "RaftSnapshot.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace WW {
PROTOBUF_CONSTEXPR SnapshotEntry::SnapshotEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SnapshotEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SnapshotEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SnapshotEntryDefaultTypeInternal() {}
  union {
    SnapshotEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SnapshotEntryDefaultTypeInternal _SnapshotEntry_default_instance_;
PROTOBUF_CONSTEXPR SnapshotData::SnapshotData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.kvs_)*/{}
  , /*decltype(_impl_.last_applied_log_index_)*/0
  , /*decltype(_impl_.last_applied_log_term_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SnapshotDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SnapshotDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SnapshotDataDefaultTypeInternal() {}
  union {
    SnapshotData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SnapshotDataDefaultTypeInternal _SnapshotData_default_instance_;
}  // namespace WW
static ::_pb::Metadata file_level_metadata_RaftSnapshot_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_RaftSnapshot_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_RaftSnapshot_2eproto = nullptr;

const uint32_t TableStruct_RaftSnapshot_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::WW::SnapshotEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::WW::SnapshotEntry, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::WW::SnapshotEntry, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::WW::SnapshotData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::WW::SnapshotData, _impl_.last_applied_log_index_),
  PROTOBUF_FIELD_OFFSET(::WW::SnapshotData, _impl_.last_applied_log_term_),
  PROTOBUF_FIELD_OFFSET(::WW::SnapshotData, _impl_.kvs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::WW::SnapshotEntry)},
  { 8, -1, -1, sizeof(::WW::SnapshotData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::WW::_SnapshotEntry_default_instance_._instance,
  &::WW::_SnapshotData_default_instance_._instance,
};

const char descriptor_table_protodef_RaftSnapshot_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022RaftSnapshot.proto\022\002WW\"+\n\rSnapshotEntr"
  "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"m\n\014Snapsho"
  "tData\022\036\n\026last_applied_log_index\030\001 \001(\005\022\035\n"
  "\025last_applied_log_term\030\002 \001(\005\022\036\n\003kvs\030\003 \003("
  "\0132\021.WW.SnapshotEntryb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_RaftSnapshot_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_RaftSnapshot_2eproto = {
    false, false, 188, descriptor_table_protodef_RaftSnapshot_2eproto,
    "RaftSnapshot.proto",
    &descriptor_table_RaftSnapshot_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_RaftSnapshot_2eproto::offsets,
    file_level_metadata_RaftSnapshot_2eproto, file_level_enum_descriptors_RaftSnapshot_2eproto,
    file_level_service_descriptors_RaftSnapshot_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_RaftSnapshot_2eproto_getter() {
  return &descriptor_table_RaftSnapshot_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_RaftSnapshot_2eproto(&descriptor_table_RaftSnapshot_2eproto);
namespace WW {

// ===================================================================

class SnapshotEntry::_Internal {
 public:
};

SnapshotEntry::SnapshotEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:WW.SnapshotEntry)
}
SnapshotEntry::SnapshotEntry(const SnapshotEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SnapshotEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:WW.SnapshotEntry)
}

inline void SnapshotEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SnapshotEntry::~SnapshotEntry() {
  // @@protoc_insertion_point(destructor:WW.SnapshotEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SnapshotEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.key_.Destroy();
  _impl_.value_.Destroy();
}

void SnapshotEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SnapshotEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:WW.SnapshotEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SnapshotEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "WW.SnapshotEntry.key"));
        } else
          goto handle_unusual;
        continue;
      // string value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "WW.SnapshotEntry.value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SnapshotEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WW.SnapshotEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "WW.SnapshotEntry.key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_key(), target);
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "WW.SnapshotEntry.value");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WW.SnapshotEntry)
  return target;
}

size_t SnapshotEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WW.SnapshotEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SnapshotEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SnapshotEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SnapshotEntry::GetClassData() const { return &_class_data_; }


void SnapshotEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SnapshotEntry*>(&to_msg);
  auto& from = static_cast<const SnapshotEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:WW.SnapshotEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SnapshotEntry::CopyFrom(const SnapshotEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WW.SnapshotEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SnapshotEntry::IsInitialized() const {
  return true;
}

void SnapshotEntry::InternalSwap(SnapshotEntry* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value_, lhs_arena,
      &other->_impl_.value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SnapshotEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RaftSnapshot_2eproto_getter, &descriptor_table_RaftSnapshot_2eproto_once,
      file_level_metadata_RaftSnapshot_2eproto[0]);
}

// ===================================================================

class SnapshotData::_Internal {
 public:
};

SnapshotData::SnapshotData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:WW.SnapshotData)
}
SnapshotData::SnapshotData(const SnapshotData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SnapshotData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.kvs_){from._impl_.kvs_}
    , decltype(_impl_.last_applied_log_index_){}
    , decltype(_impl_.last_applied_log_term_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.last_applied_log_index_, &from._impl_.last_applied_log_index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.last_applied_log_term_) -
    reinterpret_cast<char*>(&_impl_.last_applied_log_index_)) + sizeof(_impl_.last_applied_log_term_));
  // @@protoc_insertion_point(copy_constructor:WW.SnapshotData)
}

inline void SnapshotData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.kvs_){arena}
    , decltype(_impl_.last_applied_log_index_){0}
    , decltype(_impl_.last_applied_log_term_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SnapshotData::~SnapshotData() {
  // @@protoc_insertion_point(destructor:WW.SnapshotData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SnapshotData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.kvs_.~RepeatedPtrField();
}

void SnapshotData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SnapshotData::Clear() {
// @@protoc_insertion_point(message_clear_start:WW.SnapshotData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.kvs_.Clear();
  ::memset(&_impl_.last_applied_log_index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.last_applied_log_term_) -
      reinterpret_cast<char*>(&_impl_.last_applied_log_index_)) + sizeof(_impl_.last_applied_log_term_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SnapshotData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 last_applied_log_index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.last_applied_log_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 last_applied_log_term = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.last_applied_log_term_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .WW.SnapshotEntry kvs = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_kvs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SnapshotData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WW.SnapshotData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 last_applied_log_index = 1;
  if (this->_internal_last_applied_log_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_last_applied_log_index(), target);
  }

  // int32 last_applied_log_term = 2;
  if (this->_internal_last_applied_log_term() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_last_applied_log_term(), target);
  }

  // repeated .WW.SnapshotEntry kvs = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_kvs_size()); i < n; i++) {
    const auto& repfield = this->_internal_kvs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WW.SnapshotData)
  return target;
}

size_t SnapshotData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WW.SnapshotData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .WW.SnapshotEntry kvs = 3;
  total_size += 1UL * this->_internal_kvs_size();
  for (const auto& msg : this->_impl_.kvs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 last_applied_log_index = 1;
  if (this->_internal_last_applied_log_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_last_applied_log_index());
  }

  // int32 last_applied_log_term = 2;
  if (this->_internal_last_applied_log_term() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_last_applied_log_term());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SnapshotData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SnapshotData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SnapshotData::GetClassData() const { return &_class_data_; }


void SnapshotData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SnapshotData*>(&to_msg);
  auto& from = static_cast<const SnapshotData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:WW.SnapshotData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.kvs_.MergeFrom(from._impl_.kvs_);
  if (from._internal_last_applied_log_index() != 0) {
    _this->_internal_set_last_applied_log_index(from._internal_last_applied_log_index());
  }
  if (from._internal_last_applied_log_term() != 0) {
    _this->_internal_set_last_applied_log_term(from._internal_last_applied_log_term());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SnapshotData::CopyFrom(const SnapshotData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WW.SnapshotData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SnapshotData::IsInitialized() const {
  return true;
}

void SnapshotData::InternalSwap(SnapshotData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.kvs_.InternalSwap(&other->_impl_.kvs_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SnapshotData, _impl_.last_applied_log_term_)
      + sizeof(SnapshotData::_impl_.last_applied_log_term_)
      - PROTOBUF_FIELD_OFFSET(SnapshotData, _impl_.last_applied_log_index_)>(
          reinterpret_cast<char*>(&_impl_.last_applied_log_index_),
          reinterpret_cast<char*>(&other->_impl_.last_applied_log_index_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SnapshotData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RaftSnapshot_2eproto_getter, &descriptor_table_RaftSnapshot_2eproto_once,
      file_level_metadata_RaftSnapshot_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace WW
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::WW::SnapshotEntry*
Arena::CreateMaybeMessage< ::WW::SnapshotEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WW::SnapshotEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::WW::SnapshotData*
Arena::CreateMaybeMessage< ::WW::SnapshotData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WW::SnapshotData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
