// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RaftRpcData.proto

#include "RaftRpcData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace WW {
PROTOBUF_CONSTEXPR RaftRpcData::RaftRpcData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.service_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.method_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.payload_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sequence_id_)*/uint64_t{0u}
  , /*decltype(_impl_.payload_size_)*/0u
  , /*decltype(_impl_.payload_checksum_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RaftRpcDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RaftRpcDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RaftRpcDataDefaultTypeInternal() {}
  union {
    RaftRpcData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RaftRpcDataDefaultTypeInternal _RaftRpcData_default_instance_;
}  // namespace WW
static ::_pb::Metadata file_level_metadata_RaftRpcData_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_RaftRpcData_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_RaftRpcData_2eproto = nullptr;

const uint32_t TableStruct_RaftRpcData_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::WW::RaftRpcData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::WW::RaftRpcData, _impl_.service_name_),
  PROTOBUF_FIELD_OFFSET(::WW::RaftRpcData, _impl_.method_name_),
  PROTOBUF_FIELD_OFFSET(::WW::RaftRpcData, _impl_.sequence_id_),
  PROTOBUF_FIELD_OFFSET(::WW::RaftRpcData, _impl_.payload_size_),
  PROTOBUF_FIELD_OFFSET(::WW::RaftRpcData, _impl_.payload_checksum_),
  PROTOBUF_FIELD_OFFSET(::WW::RaftRpcData, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::WW::RaftRpcData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::WW::_RaftRpcData_default_instance_._instance,
};

const char descriptor_table_protodef_RaftRpcData_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021RaftRpcData.proto\022\002WW\"\216\001\n\013RaftRpcData\022"
  "\024\n\014service_name\030\001 \001(\t\022\023\n\013method_name\030\002 \001"
  "(\t\022\023\n\013sequence_id\030\003 \001(\006\022\024\n\014payload_size\030"
  "\004 \001(\007\022\030\n\020payload_checksum\030\005 \001(\007\022\017\n\007paylo"
  "ad\030\006 \001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_RaftRpcData_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_RaftRpcData_2eproto = {
    false, false, 176, descriptor_table_protodef_RaftRpcData_2eproto,
    "RaftRpcData.proto",
    &descriptor_table_RaftRpcData_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_RaftRpcData_2eproto::offsets,
    file_level_metadata_RaftRpcData_2eproto, file_level_enum_descriptors_RaftRpcData_2eproto,
    file_level_service_descriptors_RaftRpcData_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_RaftRpcData_2eproto_getter() {
  return &descriptor_table_RaftRpcData_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_RaftRpcData_2eproto(&descriptor_table_RaftRpcData_2eproto);
namespace WW {

// ===================================================================

class RaftRpcData::_Internal {
 public:
};

RaftRpcData::RaftRpcData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:WW.RaftRpcData)
}
RaftRpcData::RaftRpcData(const RaftRpcData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RaftRpcData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.service_name_){}
    , decltype(_impl_.method_name_){}
    , decltype(_impl_.payload_){}
    , decltype(_impl_.sequence_id_){}
    , decltype(_impl_.payload_size_){}
    , decltype(_impl_.payload_checksum_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.service_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.service_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_service_name().empty()) {
    _this->_impl_.service_name_.Set(from._internal_service_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.method_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.method_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_method_name().empty()) {
    _this->_impl_.method_name_.Set(from._internal_method_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_payload().empty()) {
    _this->_impl_.payload_.Set(from._internal_payload(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.sequence_id_, &from._impl_.sequence_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.payload_checksum_) -
    reinterpret_cast<char*>(&_impl_.sequence_id_)) + sizeof(_impl_.payload_checksum_));
  // @@protoc_insertion_point(copy_constructor:WW.RaftRpcData)
}

inline void RaftRpcData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.service_name_){}
    , decltype(_impl_.method_name_){}
    , decltype(_impl_.payload_){}
    , decltype(_impl_.sequence_id_){uint64_t{0u}}
    , decltype(_impl_.payload_size_){0u}
    , decltype(_impl_.payload_checksum_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.service_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.service_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.method_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.method_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RaftRpcData::~RaftRpcData() {
  // @@protoc_insertion_point(destructor:WW.RaftRpcData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RaftRpcData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.service_name_.Destroy();
  _impl_.method_name_.Destroy();
  _impl_.payload_.Destroy();
}

void RaftRpcData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RaftRpcData::Clear() {
// @@protoc_insertion_point(message_clear_start:WW.RaftRpcData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.service_name_.ClearToEmpty();
  _impl_.method_name_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  ::memset(&_impl_.sequence_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.payload_checksum_) -
      reinterpret_cast<char*>(&_impl_.sequence_id_)) + sizeof(_impl_.payload_checksum_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RaftRpcData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string service_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_service_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "WW.RaftRpcData.service_name"));
        } else
          goto handle_unusual;
        continue;
      // string method_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_method_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "WW.RaftRpcData.method_name"));
        } else
          goto handle_unusual;
        continue;
      // fixed64 sequence_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.sequence_id_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint64_t>(ptr);
          ptr += sizeof(uint64_t);
        } else
          goto handle_unusual;
        continue;
      // fixed32 payload_size = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.payload_size_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint32_t>(ptr);
          ptr += sizeof(uint32_t);
        } else
          goto handle_unusual;
        continue;
      // fixed32 payload_checksum = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.payload_checksum_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<uint32_t>(ptr);
          ptr += sizeof(uint32_t);
        } else
          goto handle_unusual;
        continue;
      // bytes payload = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_payload();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RaftRpcData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WW.RaftRpcData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string service_name = 1;
  if (!this->_internal_service_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_service_name().data(), static_cast<int>(this->_internal_service_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "WW.RaftRpcData.service_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_service_name(), target);
  }

  // string method_name = 2;
  if (!this->_internal_method_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_method_name().data(), static_cast<int>(this->_internal_method_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "WW.RaftRpcData.method_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_method_name(), target);
  }

  // fixed64 sequence_id = 3;
  if (this->_internal_sequence_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed64ToArray(3, this->_internal_sequence_id(), target);
  }

  // fixed32 payload_size = 4;
  if (this->_internal_payload_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed32ToArray(4, this->_internal_payload_size(), target);
  }

  // fixed32 payload_checksum = 5;
  if (this->_internal_payload_checksum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFixed32ToArray(5, this->_internal_payload_checksum(), target);
  }

  // bytes payload = 6;
  if (!this->_internal_payload().empty()) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_payload(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WW.RaftRpcData)
  return target;
}

size_t RaftRpcData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WW.RaftRpcData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string service_name = 1;
  if (!this->_internal_service_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_service_name());
  }

  // string method_name = 2;
  if (!this->_internal_method_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_method_name());
  }

  // bytes payload = 6;
  if (!this->_internal_payload().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_payload());
  }

  // fixed64 sequence_id = 3;
  if (this->_internal_sequence_id() != 0) {
    total_size += 1 + 8;
  }

  // fixed32 payload_size = 4;
  if (this->_internal_payload_size() != 0) {
    total_size += 1 + 4;
  }

  // fixed32 payload_checksum = 5;
  if (this->_internal_payload_checksum() != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RaftRpcData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RaftRpcData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RaftRpcData::GetClassData() const { return &_class_data_; }


void RaftRpcData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RaftRpcData*>(&to_msg);
  auto& from = static_cast<const RaftRpcData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:WW.RaftRpcData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_service_name().empty()) {
    _this->_internal_set_service_name(from._internal_service_name());
  }
  if (!from._internal_method_name().empty()) {
    _this->_internal_set_method_name(from._internal_method_name());
  }
  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  if (from._internal_sequence_id() != 0) {
    _this->_internal_set_sequence_id(from._internal_sequence_id());
  }
  if (from._internal_payload_size() != 0) {
    _this->_internal_set_payload_size(from._internal_payload_size());
  }
  if (from._internal_payload_checksum() != 0) {
    _this->_internal_set_payload_checksum(from._internal_payload_checksum());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RaftRpcData::CopyFrom(const RaftRpcData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WW.RaftRpcData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RaftRpcData::IsInitialized() const {
  return true;
}

void RaftRpcData::InternalSwap(RaftRpcData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.service_name_, lhs_arena,
      &other->_impl_.service_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.method_name_, lhs_arena,
      &other->_impl_.method_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.payload_, lhs_arena,
      &other->_impl_.payload_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RaftRpcData, _impl_.payload_checksum_)
      + sizeof(RaftRpcData::_impl_.payload_checksum_)
      - PROTOBUF_FIELD_OFFSET(RaftRpcData, _impl_.sequence_id_)>(
          reinterpret_cast<char*>(&_impl_.sequence_id_),
          reinterpret_cast<char*>(&other->_impl_.sequence_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RaftRpcData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RaftRpcData_2eproto_getter, &descriptor_table_RaftRpcData_2eproto_once,
      file_level_metadata_RaftRpcData_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace WW
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::WW::RaftRpcData*
Arena::CreateMaybeMessage< ::WW::RaftRpcData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WW::RaftRpcData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
