// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RaftPersist.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_RaftPersist_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_RaftPersist_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RaftPersist_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_RaftPersist_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RaftPersist_2eproto;
namespace WW {
class RaftPersistData;
struct RaftPersistDataDefaultTypeInternal;
extern RaftPersistDataDefaultTypeInternal _RaftPersistData_default_instance_;
class RaftPersistLogEntry;
struct RaftPersistLogEntryDefaultTypeInternal;
extern RaftPersistLogEntryDefaultTypeInternal _RaftPersistLogEntry_default_instance_;
}  // namespace WW
PROTOBUF_NAMESPACE_OPEN
template<> ::WW::RaftPersistData* Arena::CreateMaybeMessage<::WW::RaftPersistData>(Arena*);
template<> ::WW::RaftPersistLogEntry* Arena::CreateMaybeMessage<::WW::RaftPersistLogEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace WW {

// ===================================================================

class RaftPersistLogEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:WW.RaftPersistLogEntry) */ {
 public:
  inline RaftPersistLogEntry() : RaftPersistLogEntry(nullptr) {}
  ~RaftPersistLogEntry() override;
  explicit PROTOBUF_CONSTEXPR RaftPersistLogEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftPersistLogEntry(const RaftPersistLogEntry& from);
  RaftPersistLogEntry(RaftPersistLogEntry&& from) noexcept
    : RaftPersistLogEntry() {
    *this = ::std::move(from);
  }

  inline RaftPersistLogEntry& operator=(const RaftPersistLogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftPersistLogEntry& operator=(RaftPersistLogEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftPersistLogEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftPersistLogEntry* internal_default_instance() {
    return reinterpret_cast<const RaftPersistLogEntry*>(
               &_RaftPersistLogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RaftPersistLogEntry& a, RaftPersistLogEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftPersistLogEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftPersistLogEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftPersistLogEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftPersistLogEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftPersistLogEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftPersistLogEntry& from) {
    RaftPersistLogEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftPersistLogEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "WW.RaftPersistLogEntry";
  }
  protected:
  explicit RaftPersistLogEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandFieldNumber = 2,
    kTermFieldNumber = 1,
  };
  // bytes command = 2;
  void clear_command();
  const std::string& command() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command();
  PROTOBUF_NODISCARD std::string* release_command();
  void set_allocated_command(std::string* command);
  private:
  const std::string& _internal_command() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command(const std::string& value);
  std::string* _internal_mutable_command();
  public:

  // int64 term = 1;
  void clear_term();
  int64_t term() const;
  void set_term(int64_t value);
  private:
  int64_t _internal_term() const;
  void _internal_set_term(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:WW.RaftPersistLogEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_;
    int64_t term_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftPersist_2eproto;
};
// -------------------------------------------------------------------

class RaftPersistData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:WW.RaftPersistData) */ {
 public:
  inline RaftPersistData() : RaftPersistData(nullptr) {}
  ~RaftPersistData() override;
  explicit PROTOBUF_CONSTEXPR RaftPersistData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftPersistData(const RaftPersistData& from);
  RaftPersistData(RaftPersistData&& from) noexcept
    : RaftPersistData() {
    *this = ::std::move(from);
  }

  inline RaftPersistData& operator=(const RaftPersistData& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftPersistData& operator=(RaftPersistData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftPersistData& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftPersistData* internal_default_instance() {
    return reinterpret_cast<const RaftPersistData*>(
               &_RaftPersistData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RaftPersistData& a, RaftPersistData& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftPersistData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftPersistData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftPersistData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftPersistData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftPersistData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftPersistData& from) {
    RaftPersistData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftPersistData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "WW.RaftPersistData";
  }
  protected:
  explicit RaftPersistData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 3,
    kTermFieldNumber = 1,
    kVotedForFieldNumber = 2,
    kLastIncludedIndexFieldNumber = 4,
    kLastIncludedTermFieldNumber = 5,
  };
  // repeated .WW.RaftPersistLogEntry entries = 3;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  ::WW::RaftPersistLogEntry* mutable_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::WW::RaftPersistLogEntry >*
      mutable_entries();
  private:
  const ::WW::RaftPersistLogEntry& _internal_entries(int index) const;
  ::WW::RaftPersistLogEntry* _internal_add_entries();
  public:
  const ::WW::RaftPersistLogEntry& entries(int index) const;
  ::WW::RaftPersistLogEntry* add_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::WW::RaftPersistLogEntry >&
      entries() const;

  // int64 term = 1;
  void clear_term();
  int64_t term() const;
  void set_term(int64_t value);
  private:
  int64_t _internal_term() const;
  void _internal_set_term(int64_t value);
  public:

  // int64 voted_for = 2;
  void clear_voted_for();
  int64_t voted_for() const;
  void set_voted_for(int64_t value);
  private:
  int64_t _internal_voted_for() const;
  void _internal_set_voted_for(int64_t value);
  public:

  // int64 last_included_index = 4;
  void clear_last_included_index();
  int64_t last_included_index() const;
  void set_last_included_index(int64_t value);
  private:
  int64_t _internal_last_included_index() const;
  void _internal_set_last_included_index(int64_t value);
  public:

  // int64 last_included_term = 5;
  void clear_last_included_term();
  int64_t last_included_term() const;
  void set_last_included_term(int64_t value);
  private:
  int64_t _internal_last_included_term() const;
  void _internal_set_last_included_term(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:WW.RaftPersistData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::WW::RaftPersistLogEntry > entries_;
    int64_t term_;
    int64_t voted_for_;
    int64_t last_included_index_;
    int64_t last_included_term_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RaftPersist_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RaftPersistLogEntry

// int64 term = 1;
inline void RaftPersistLogEntry::clear_term() {
  _impl_.term_ = int64_t{0};
}
inline int64_t RaftPersistLogEntry::_internal_term() const {
  return _impl_.term_;
}
inline int64_t RaftPersistLogEntry::term() const {
  // @@protoc_insertion_point(field_get:WW.RaftPersistLogEntry.term)
  return _internal_term();
}
inline void RaftPersistLogEntry::_internal_set_term(int64_t value) {
  
  _impl_.term_ = value;
}
inline void RaftPersistLogEntry::set_term(int64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:WW.RaftPersistLogEntry.term)
}

// bytes command = 2;
inline void RaftPersistLogEntry::clear_command() {
  _impl_.command_.ClearToEmpty();
}
inline const std::string& RaftPersistLogEntry::command() const {
  // @@protoc_insertion_point(field_get:WW.RaftPersistLogEntry.command)
  return _internal_command();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftPersistLogEntry::set_command(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:WW.RaftPersistLogEntry.command)
}
inline std::string* RaftPersistLogEntry::mutable_command() {
  std::string* _s = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:WW.RaftPersistLogEntry.command)
  return _s;
}
inline const std::string& RaftPersistLogEntry::_internal_command() const {
  return _impl_.command_.Get();
}
inline void RaftPersistLogEntry::_internal_set_command(const std::string& value) {
  
  _impl_.command_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftPersistLogEntry::_internal_mutable_command() {
  
  return _impl_.command_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftPersistLogEntry::release_command() {
  // @@protoc_insertion_point(field_release:WW.RaftPersistLogEntry.command)
  return _impl_.command_.Release();
}
inline void RaftPersistLogEntry::set_allocated_command(std::string* command) {
  if (command != nullptr) {
    
  } else {
    
  }
  _impl_.command_.SetAllocated(command, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_.IsDefault()) {
    _impl_.command_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:WW.RaftPersistLogEntry.command)
}

// -------------------------------------------------------------------

// RaftPersistData

// int64 term = 1;
inline void RaftPersistData::clear_term() {
  _impl_.term_ = int64_t{0};
}
inline int64_t RaftPersistData::_internal_term() const {
  return _impl_.term_;
}
inline int64_t RaftPersistData::term() const {
  // @@protoc_insertion_point(field_get:WW.RaftPersistData.term)
  return _internal_term();
}
inline void RaftPersistData::_internal_set_term(int64_t value) {
  
  _impl_.term_ = value;
}
inline void RaftPersistData::set_term(int64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:WW.RaftPersistData.term)
}

// int64 voted_for = 2;
inline void RaftPersistData::clear_voted_for() {
  _impl_.voted_for_ = int64_t{0};
}
inline int64_t RaftPersistData::_internal_voted_for() const {
  return _impl_.voted_for_;
}
inline int64_t RaftPersistData::voted_for() const {
  // @@protoc_insertion_point(field_get:WW.RaftPersistData.voted_for)
  return _internal_voted_for();
}
inline void RaftPersistData::_internal_set_voted_for(int64_t value) {
  
  _impl_.voted_for_ = value;
}
inline void RaftPersistData::set_voted_for(int64_t value) {
  _internal_set_voted_for(value);
  // @@protoc_insertion_point(field_set:WW.RaftPersistData.voted_for)
}

// repeated .WW.RaftPersistLogEntry entries = 3;
inline int RaftPersistData::_internal_entries_size() const {
  return _impl_.entries_.size();
}
inline int RaftPersistData::entries_size() const {
  return _internal_entries_size();
}
inline void RaftPersistData::clear_entries() {
  _impl_.entries_.Clear();
}
inline ::WW::RaftPersistLogEntry* RaftPersistData::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:WW.RaftPersistData.entries)
  return _impl_.entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::WW::RaftPersistLogEntry >*
RaftPersistData::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:WW.RaftPersistData.entries)
  return &_impl_.entries_;
}
inline const ::WW::RaftPersistLogEntry& RaftPersistData::_internal_entries(int index) const {
  return _impl_.entries_.Get(index);
}
inline const ::WW::RaftPersistLogEntry& RaftPersistData::entries(int index) const {
  // @@protoc_insertion_point(field_get:WW.RaftPersistData.entries)
  return _internal_entries(index);
}
inline ::WW::RaftPersistLogEntry* RaftPersistData::_internal_add_entries() {
  return _impl_.entries_.Add();
}
inline ::WW::RaftPersistLogEntry* RaftPersistData::add_entries() {
  ::WW::RaftPersistLogEntry* _add = _internal_add_entries();
  // @@protoc_insertion_point(field_add:WW.RaftPersistData.entries)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::WW::RaftPersistLogEntry >&
RaftPersistData::entries() const {
  // @@protoc_insertion_point(field_list:WW.RaftPersistData.entries)
  return _impl_.entries_;
}

// int64 last_included_index = 4;
inline void RaftPersistData::clear_last_included_index() {
  _impl_.last_included_index_ = int64_t{0};
}
inline int64_t RaftPersistData::_internal_last_included_index() const {
  return _impl_.last_included_index_;
}
inline int64_t RaftPersistData::last_included_index() const {
  // @@protoc_insertion_point(field_get:WW.RaftPersistData.last_included_index)
  return _internal_last_included_index();
}
inline void RaftPersistData::_internal_set_last_included_index(int64_t value) {
  
  _impl_.last_included_index_ = value;
}
inline void RaftPersistData::set_last_included_index(int64_t value) {
  _internal_set_last_included_index(value);
  // @@protoc_insertion_point(field_set:WW.RaftPersistData.last_included_index)
}

// int64 last_included_term = 5;
inline void RaftPersistData::clear_last_included_term() {
  _impl_.last_included_term_ = int64_t{0};
}
inline int64_t RaftPersistData::_internal_last_included_term() const {
  return _impl_.last_included_term_;
}
inline int64_t RaftPersistData::last_included_term() const {
  // @@protoc_insertion_point(field_get:WW.RaftPersistData.last_included_term)
  return _internal_last_included_term();
}
inline void RaftPersistData::_internal_set_last_included_term(int64_t value) {
  
  _impl_.last_included_term_ = value;
}
inline void RaftPersistData::set_last_included_term(int64_t value) {
  _internal_set_last_included_term(value);
  // @@protoc_insertion_point(field_set:WW.RaftPersistData.last_included_term)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace WW

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_RaftPersist_2eproto
